# Generated by Django 5.2.13 on 2026-04-12 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('terapevt', 'Terapevt'), ('kardiolog', 'Kardiolog'), ('nevrolog', 'Nevrolog'), ('xirurg', 'Xirurg'), ('oftalmolog', 'Oftalmolog'), ('dermatolog', 'Dermatolog'), ('pediatr', 'Pediatr'), ('ginekolog', 'Ginekolog'), ('ortoped', 'Ortoped'), ('endokrinolog', 'Endokrinolog'), ('pulmonolog', 'Pulmonolog'), ('gastroenterolog', 'Gastroenterolog'), ('psixiatr', 'Psixiatr'), ('urolog', 'Urolog'), ('onkolog', 'Onkolog')], default='terapevt', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doktor profili',
                'verbose_name_plural': 'Doktor profillari',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A(II)+'), ('A-', 'A(II)-'), ('B+', 'B(III)+'), ('B-', 'B(III)-'), ('AB+', 'AB(IV)+'), ('AB-', 'AB(IV)-'), ('O+', 'O(I)+'), ('O-', 'O(I)-')], max_length=5)),
                ('allergies', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='core.doctorprofile')),
            ],
            options={
                'verbose_name': 'Bemor',
                'verbose_name_plural': 'Bemorlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200)),
                ('icd_code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('symptoms', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('yangi', 'Yangi'), ('davolanyapti', 'Davolanyapti'), ('yaxshilandi', 'Yaxshilandi'), ('tuzaldi', 'Tuzaldi'), ('surunkali', 'Surunkali')], default='yangi', max_length=20)),
                ('severity', models.CharField(choices=[('engil', 'Engil'), ('orta', "O'rta"), ('ogir', "Og'ir"), ('juda_ogir', "Juda og'ir")], default='orta', max_length=20)),
                ('diagnosis_date', models.DateField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='core.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='core.patient')),
            ],
            options={
                'verbose_name': 'Tashxis',
                'verbose_name_plural': 'Tashxislar',
                'ordering': ['-created_at'],
            },
        ),
    ]
